Set eip4844 blob limits to 1/2
gnosischain/specs pull request #24
Opened 2023-10-11 12:13 UTC by dapplion

**Big blocks experiment summary**

![photo_2023-10-05_08-21-52](https://github.com/gnosischain/specs/assets/35266934/dde20046-5ca8-4c30-8301-87ecdbcd206c)

Noticeable degradation on the bucket 250-500Kb. Tolerable degradation on 130-262Kb. 

Full doc to follow

**Comparision to Ethereum rate**

Per time rate = `3 * 5/12 / 6 * 5/12` = `1.25 / 2.5`

**Proposal**

1/2 is a conservation choice that should not increase network latency beyond key thresholds. Increasing this values can be done latter in response to demand and only requires changes on the execution layer clients.

Closes https://github.com/gnosischain/specs/issues/18

2023-10-11 12:23 UTC, 4rgon4ut approved these changes

2023-10-11 12:26 UTC, 4rgon4ut commented
@dapplion Looks good!
> Full doc to follow

Is there supposed to be a link?

2023-10-12 13:10 UTC, yperbasis requested changes
I believe that in that case `DATA_GASPRICE_UPDATE_FRACTION` should be set to 2225652. Refer to https://github.com/ethereum/EIPs/pull/7154

2023-10-12 13:13 UTC, yperbasis commented
> DATA_GASPRICE_UPDATE_FRACTION

Actually, sorry, 2225652 was the value for 2/4. We need to calculate the correct value for 1/2.

2023-10-12 15:55 UTC, yperbasis commented
`BLOB_GASPRICE_UPDATE_FRACTION` should be set to 1112826 so that `e(TARGET_BLOB_GAS_PER_BLOCK / BLOB_GASPRICE_UPDATE_FRACTION) ≈ 1.125` still holds.

2023-10-17 08:54 UTC, yperbasis approved these changes

2023-10-18 11:43 UTC, 4rgon4ut commented
[1/2 justification from network load perspective ](https://hackmd.io/@5qNKk0aeQlygax4hX3rVXw/SkY3dBV-6)

2023-10-18 12:23 UTC, merged